#
# Travis CI configuration file for HTMLDOC.
#

language: c

env:
  global:
    - secure: "NROKLX5SdoS/XHewL0BB3NYFHIBkwpRbdDgeqsxV3AoB5qgKA/pOTyZC+W+ez0T3oGYbzZXS5aSGDoEZkEeK6lSZlQ49Q45AZNaxFkf/RHfd0+QQY4NQ4IDSIohyWf4/+GTuB4pQc+1gOU35JKnvc8kyCuJBZZsfH0Ja0O2mT5OybbkbiPPM4rqk6bXEqMqEL4+emARvD6c4olpHHlmWeDRUQfQy65tDmNyQlKqjFaMY4jwUYkZdgLZMW1ywMfprZWhI5rrktnazXnPGVx5s7ZEBrhtRSwkc/1RvGslDqd1CWkN2OlrCFx9ewOIdiRsp1kbVAYE2UR8CtQEMK5PPvyUx/1+h3TqBtw5eZN/jeAXvqyAE2CCyu9TU0jRaljcOQFYQUW5RGvo57MYNc5TNK5II9r3A8YosEF5e9E/4J5vQHvJUwAQx4Uj8IuQUm4fpLhkCq6fqdBW5UzYembRBU2IaOkRHicQuztHybYyQCnN53zoT3v3zbFeZNTEVNjjR93i5duuhQTjVXnVyrITRoNLHT2TxEXRXzp/fHOOydbPdYHpuTfbrOM+YpG5gOUmZ/gUQtzkyH3WwM+emGwgoMzVudTVX7bA8PiNsCT5DsWDj8ALjjNwW2rmxHJBWbvo665jdh4G5Yv9XUOi+/7C/et8YHuaPqRx+wBSCECgzctA="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

script: ./configure --enable-debug --enable-maintainer && make

addons:
  apt:
    packages: [cppcheck, libgnutls28-dev]

addons:
  coverity_scan:
    project:
      name: "michaelrsweet/htmldoc"
      description: "HTML conversion utility"
    notification_email: michael.r.sweet@gmail.com
    build_command_prepend: "make clean"
    build_command: "make"
    branch_pattern: coverity_scan

notifications:
  email:
    recipients:
      - msweet@msweet.org
