name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout htmldoc sources
      uses: actions/checkout@v4
    - name: Update build environment
      run: sudo apt-get update --fix-missing -y
    - name: Install prerequisites
      run: sudo apt-get install -y cppcheck libfltk1.3-dev libcups2-dev libjpeg-dev libpng-dev zlib1g-dev
    - name: Configure htmldoc
      env:
        CC: /usr/bin/gcc
      run: ./configure --enable-debug
    - name: Build htmldoc
      run: make

  build-macos:

    runs-on: macos-latest

    steps:
    - name: Checkout htmldoc sources
      uses: actions/checkout@v4
    - name: Install prerequisites
      run: brew install cppcheck fltk libjpeg libpng
    - name: Configure htmldoc
      run: ./configure --enable-debug --enable-maintainer --enable-sanitizer
    - name: Build htmldoc
      run: make

  build-windows:

    runs-on: windows-latest

    steps:
    - name: Checkout htmldoc sources
      uses: actions/checkout@v4
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v2
    - name: Install prerequisites
      run: cd vcnet; nuget restore htmldoc.sln
    - name: Build htmldoc
      run: cd vcnet; msbuild htmldoc.sln -t:htmldoc -t:ghtmldoc
