name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update build environment
      run: sudo apt-get update --fix-missing -y
    - name: install prerequisites
      run: sudo apt-get install -y cppcheck libfltk1.3-dev libgnutls28-dev libjpeg-dev libpng-dev zlib1g-dev
    - name: configure
      env:
        CC: /usr/bin/gcc
      run: ./configure --enable-debug
    - name: make
      run: make

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: install prerequisites
      run: brew install cppcheck fltk libjpeg libpng
    - name: configure
      run: ./configure --enable-debug --enable-maintainer --enable-sanitizer
    - name: make
      run: make

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: nuget restore
      run: cd vcnet; nuget restore htmldoc.sln
    - name: msbuild
      run: cd vcnet; msbuild htmldoc.sln -t:htmldoc -t:ghtmldoc
